### ISSUE TITLE
Way to disable per-container memory limit in task definition

### ISSUE THREAD

**Issue by robbyt** [aws/amazon-ecs-agent#155]
According to the docs[1], the per-container memory limit is required. This is inconvenient, because I use the same ElasticBeanstalk `Dockerrun.aws.json` file with multiple instance types.

Is there a way to disable this setting?

[1]: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html

**Comment by euank** [comment]
You're correct that there's currently no way to disable this requirement.

There is some discussion in #124 about memory limits and we're internally tracking the feature request of percentage / proportional memory limits.

Would being able to specify a proportional amount of memory and/or being able to overcommit memory resolve the issue for you?
Do you want to just be able to opt out of setting memory and having it tracked/scheduled upon at all?

**Comment by robbyt** [comment]
@euank yes, a percentage/proportional amount of memory would be the best solution. I can imagine that overcommit might confuse people.

Disabling the memory setting would be a quick fix for my use case, but I think a memory percentage setting is the best solution.

**Comment by 0xadada** [comment]
i'm also interested in this discussion.

**Comment by pmcjury** [comment]
:thumbsup:

**Comment by morgante** [comment]
Having this is kind of a deal-breaker for us.

We're running multiple services in our cluster. Each service by itself usually uses very little memory but occasionally spikes while processing a request. When it spikes, it needs nearly the entire instance's memory. However, services never spike at the same time.

As it is, there doesn't seem to be any way to provision this kind of setup using ECS.

Being able to disable resource limits would be hugely beneficial for us.

**Comment by vad** [comment]
We need this too, because the OS enables the oom-killer when the containers goes above the threshold, and the oom-killer can kill containers "randomly" (and even processes in the host, not only containers). This happened us twice: a machine (host) stopped responding because a container went above the threshold!

**Comment by chenliu0831** [comment]
+1. Need this

**Comment by gabrianoo** [comment]
+1. Need this

**Comment by leftclickben** [comment]
:+1: Please make the memory limit optional.  I have a similar situation as described above; services can spike but not simultaneously.

**Comment by mr337** [comment]
+1

**Comment by jawadst** [comment]
+1
It's often the case that we run 1 task per EC2 instance and want the container to simply have access to all the memory

**Comment by razitz** [comment]
+!

**Comment by asktomsk** [comment]
+1

**Comment by parajanoff** [comment]
+1

**Comment by echery** [comment]
:+1:

**Comment by TheTweak** [comment]
+1

**Comment by alexmac** [comment]
+1 for opting out of memory limit enforcement - I want to tightly pack services onto a small "dev" ec2 instance for debugging purposes

**Comment by bribroder** [comment]
+1

**Comment by pparth** [comment]
+1

**Comment by ynelin** [comment]
+1 
In Docker there is everything for our request
https://docs.docker.com/engine/reference/run/#memory-constraints

**Comment by kyr7** [comment]
+1

**Comment by CameronGo** [comment]
+1

**Comment by ChrisRut** [comment]
+1

**Comment by mjaverto** [comment]
+1

**Comment by rjdavis3** [comment]
+1

**Comment by kswope** [comment]
+1

**Comment by asktomsk** [comment]
Almost 6 moths passed since robbyt opened this issue...

**Comment by ccosgroveOtreva** [comment]
+1

**Comment by jedimonkey** [comment]
+1

**Comment by aldarund** [comment]
+1.. so sad that such issues opened that long ago without any movements

**Comment by nanotkarashish** [comment]
+1

**Comment by tallavi** [comment]
+1

**Comment by tisinno** [comment]
+1 At least allow different settings for scheduling purposes and the oom kill threshold

**Comment by vad** [comment]
yes, 2 different settings are the best solution

**Comment by ghaering** [comment]
After an internal discussion in our company, the lack of this feature seem to be the KO for using ECS. I suggest to have two memory limits, one for the scheduling algorithm, which is required and the other for the Docker cgroup, which can be => the former or left out entirely.

**Comment by moufatich** [comment]
+1

**Comment by petkovve** [comment]
+1

**Comment by paulrutter** [comment]
+1

**Comment by mixja** [comment]
+1

**Comment by bilalaslamseattle** [comment]
+1.

**Comment by cristianobaptista** [comment]
+1

**Comment by cchitsiang** [comment]
+1

**Comment by ryanwalls** [comment]
+1

**Comment by mesmerizingr** [comment]
+1

**Comment by JanBednarik** [comment]
+1

**Comment by toooni** [comment]
+1 
![hitsat](https://cloud.githubusercontent.com/assets/241080/14208922/1b19371a-f822-11e5-853f-2e017372a49f.png)

**Comment by elHornair** [comment]
+1

Any news on this?

**Comment by bshelton229** [comment]
:+1:

**Comment by devotox** [comment]
+1

**Comment by MaerF0x0** [comment]
@samuelkarp  @euank  How many more +1s does this need before we get a response or a solution?

**Comment by samuelkarp** [comment]
As a general rule, we don't comment on the future direction of the service, but the +1s and use case details help us understand your needs.

**Comment by mixja** [comment]
One other related annoyance is that non-essential tasks in your Task Definition are counted in your memory allocation, regardless of whether they are actually running or not.  I have a use case for a non-essential task that needs to run when other services in the task definition start, which then exists and never runs again.  So I have to allocate enough memory for the task to run and this is wasted memory I can't use anywhere else.

**Comment by devotox** [comment]
@mixja  I had the same problem and my situation may be different from yours but i fixed it by having another container build what is needed in that container. Since the container doesnt need to actually run i had the minimal memory set on there and then used the volumesFrom on my api container and had the api container then build the application. Hope that helps

**Comment by matthill** [comment]
+1

After building out a testing environment, we ran into this issue and were forced to use Elastic Beanstalk instead of ECS.

**Comment by hedless** [comment]
+1

**Comment by oddurmagg** [comment]
+1 

Best solution seems to be separating it out to 2 configuration values, one for scheduling and one for the cgroup (optional). Default behaviour could be to have the same values but allow people to override if needed. 

Also, being able to specify the cgroup value as a % of the RAM of the host would be awesome. 

When used from elastic beanstalk with multidocker setup ( which will only ever deploy a single task config to a single node), allocating a total more that 100% of the host should not be possible.

**Comment by ooleem** [comment]
+1

**Comment by reidwelliver** [comment]
+1

**Comment by DrMegavolt** [comment]
+1

**Comment by ceecer1** [comment]
+1

**Comment by erickponce** [comment]
+1

**Comment by amanzyuk** [comment]
+1

**Comment by DarkCenobyte** [comment]
+1

**Comment by atlantux** [comment]
+1

**Comment by bfil** [comment]
I've been trying to migrate to multi-docker container to be able to support multiple port mappings (since single docker containers don't allow more than one mapping...) and just found out about this issue which also prevents me from using the service.

Usually we run larger instances on production, but this forces us to specify the memory requirements in our Dockerrun file, which is usually published as a single file for each new version of the service running. This would force us to either align all environments to have the same instance sizes, or publish different Dockerrun files with the same Docker image version in it just to handle the different instance sizes based on our environments requirements.

I would expect the memory requirements to be optional or at least support percentage values.

**Comment by vinayan3** [comment]
+1. I use ECS with various size machines. I have to update the task definition all the time or have different ones for different machines. A % would work better and make my life easier.

**Comment by nadavshatz** [comment]
👍

**Comment by theikkila** [comment]
+1

**Comment by josephsiefers** [comment]
+1

**Comment by nealhardesty** [comment]
+1

**Comment by sirbotta** [comment]
+1

**Comment by djtarazona** [comment]
+1

**Comment by magnus-larsson** [comment]
+1

**Comment by PepijnK** [comment]
+1

**Comment by mattijsf** [comment]
+1

**Comment by vinayan3** [comment]
This is hopeless. It's been almost a year.

**Comment by bilalaslamseattle** [comment]
@vinayan3 yep. We moved off to Kubernetes. Never looked back. Between agent disconnects, general lack of 12-factor design and so much more, moving off of ECS is a decision I don't regret.

**Comment by vad** [comment]
ECS is hopeless! It's a dead project. My hope is that AWS will move to Kubernetes too (in some way: it should be easier to use it) or GCE will "crush" AWS

**Comment by toooni** [comment]
This looks promising: https://blog.docker.com/2016/06/azure-aws-beta/ - On the bottom of the page you can sign up for the beta.

**Comment by ynelin** [comment]
Same here :). Moved part of the services to gcloud already

**Comment by pieterlange** [comment]
FWIW, december 2015 i was tasked to setup a container hosting platform and devs were already using ECS on CoreOS. I briefly thought about moving forward with ECS but between agent disconnects and general limitations/feature incompleteness of the platform the decision to move to kubernetes was pretty easy. Never looked back. I'm not sure if amazon even cares about ECS. It seems to get the same support as their elasticsearch service (supporting existing users, but discouraging any new adopters). Maybe these new technologies are still too much of a moving target to commoditize.

**Comment by samuelkarp** [comment]
Hey everyone,

We wanted to let you know a bit about how we're planing to address this feature request.

As we understand it, the problem most people here seem to be facing is related to the fact that we use the `memory` parameter of a task definition to mean two different things:

1. A placement constraint to prevent ECS from placing applications together that require more memory in total than is available on the host
2. A hard limit, enforced by the Linux kernel, of how much memory can be allocated by the cgroup of each container

Based on the feedback we see in this thread and other customer feedback, it sounds like applications which temporarily spike in memory usage but require less at steady-state are not well served by this situation; even though they may require memory temporarily, there is a desire to set the placement based on the steady-state memory requirements rather than the spikes.

We'd like to separate placement aspects from hard limits, while preserving the ability to properly schedule and to influence applications to behave properly.  Separating placement aspects is something we can do in ECS by adjusting the task definition and we think we can accomplish the second goal of influencing application behavior through [memory reservation](https://docs.docker.com/engine/reference/run/#/user-memory-constraints).  From the Docker docs:

> Memory reservation is a kind of memory soft limit that allows for greater sharing of memory. Under normal circumstances, containers can use as much of the memory as needed and are constrained only by the hard limits set with the `-m`/`--memory` option. When memory reservation is set, Docker detects memory contention or low memory and forces containers to restrict their consumption to a reservation limit.
> [...]
> Memory reservation is a soft-limit feature and does not guarantee the limit won’t be exceeded. Instead, the feature attempts to ensure that, when memory is heavily contended for, memory is allocated based on the reservation hints/setup.

We're thinking about implementing this:
* We add a new field to the container definition called `memoryReservation` that maps to Docker's `MemoryReservation` field 
* For container definitions with `memoryReservation`, we use `memoryReservation` as the placement constraint in place of the `memory` field
* Either `memory` or `memoryReservation` is required, but both can be used together
* When `memoryReservation` is specified but `memory` is not, there is no effective hard limit on the host
* When `memory` and `memoryReservation` are both specified, `memory` must be >= `memoryReservation`

For example, the task definition would be updated as follows:
```
{
  "containerDefinitions": [
    {
      "name": "mycontainer",
      "memoryReservation": 10,
      ...
    },
    ...
  ],
  ...
```

This would translate to the Docker `HostConfig` including:
```
{
    ...
    "HostConfig": {
        ...
        "MemoryReservation": 10485760,
        ...
    },
    ...
}
```

Please let us know if this does not address your concerns.

Thanks,
Sam

**Comment by djenriquez** [comment]
Great solution!

**Comment by magnus-larsson** [comment]
Looks useful to me!

Will it be available for evaluation in near time, e.g. in a test environment or alike?

**Comment by tallavi** [comment]
> Please let us know if this does not address your concerns.

Hi Sam,

Thanks for addressing this. I'm using compose files to deploy containers. How will this configuration option be available to users like me? What will the current mem_limit field in the yaml file will be used for after this feature is implemented?

**Comment by rmbrich** [comment]
Sam - the other important aspect here is the desire to set memory by percentage - i.e. container 1 fills 75% of host, container 2 fills 10%. This is helpful when changing host VM sizes; you don't have to then manually change all Dockerrun files. See first response to OP by "euank".

**Comment by PepijnK** [comment]
> the other important aspect here is the desire to set memory by percentage
Maybe a weight? This in combination with a minimalMemory setting would be perfect. By default the memoryWeight could be 1 and minimalMemory 4mb (minimum to run docker) .

**Comment by samuelkarp** [comment]
@djenriquez and @magnus-larsson, I'm glad this will work for you!  @magnus-larsson, we are working on the timelines and will announce it here soon.

**Comment by samuelkarp** [comment]
@tallavi, I looked at the [Compose File Reference](https://docs.docker.com/compose/compose-file/) and it does not appear to yet have support for memory reservation.  I think ideally we'd want to keep the same syntax as the Compose File, but I wouldn't want to overload `mem_limit` to mean two different things and I'd still want to provide the option to set both fields.  I don't know if Docker Compose has plans to support memory reservation.  @uttarasridhar, what do you think about this?

**Comment by samuelkarp** [comment]
@rmbrich, thanks for the feedback!  From reading the comments here, it looks like the request for a percentage-based memory limit seems mostly related to people using Elastic Beanstalk's multi-container support, which uses ECS for managing the containers.  With Elastic Beanstalk, the model is to use separate instances per application such that each task run through ECS runs on the instance by itself.  In this case, a percentage-based approach seems useful: since only one task ever runs and since the size of the instances is homogeneous in the cluster, you're only defining memory limits between containers defined in the same task rather than limits between different tasks.  I think the solution we proposed above allows this use case though: you set `memoryReservation` to fit the smallest instance you expect to run on and leave `memory` unspecified; containers will be scheduled to the instances and won't be limited by a memory limit intended for a smaller instance when you use a larger instance.

In general I think a percentage-based approach can actually have some really surprising behavior.  If you were to take a task definition with `memory` specified as a percentage (say, 20%) and run it in a heterogeneous cluster, the actual amount of memory available to the containers would vary based on where the task was placed.  I don't think this is expected that a container launched on a t2.micro might have 20% of 1 GB but that same container launched on a c4.4xlarge would end up with 20% of 30 GB.

**Comment by jmenga** [comment]
Our deployment model is using EC2 Container Service and instances are homogenous for a given application in a given environment.  Therefore the percentage approach would be very useful, but we are already dealing with it now - having an absolute memoryReservation as proposed is a major step forward so enough consultation and go forth and deliver the feature :)

**Comment by tallavi** [comment]
> @tallavi, I looked at the Compose File Reference and it does not appear to yet have support for memory reservation. I think ideally we'd want to keep the same syntax as the Compose File, but I wouldn't want to overload mem_limit to mean two different things and I'd still want to provide the option to set both fields. I don't know if Docker Compose has plans to support memory reservation. @uttarasridhar, what do you think about this?

@samuelkarp, will it be awful to add this field to the yaml even if the official format doesn't have it? Another posibility I can think of is to disable hard memory limits at task/service scope, meaning, to have an option for the ecs-cli compose command that starts the task/service without memory limits.

**Comment by benjaminwai** [comment]
+1 memoryReservation.

**Comment by akvadrako** [comment]
We also need this feature and though the proposed design with `memoryReservation` would give us enough control, the naming and interaction between the two fields is confusing. More intuitively, I would propose `minimum` and `maximum` fields, either like:

```json
{
  "memoryMinimum": 5,
  "memoryMaximum": 10
}
```

or even better:

```json
{
  "memory": { "min": 5, "max": 10 }
}
```

So a system must have at least `min` for the task to be scheduled and that amount will be reserved. Also, the task will be limited to `max` usage.

**Comment by tallavi** [comment]
> So a system must have at least min for the task to be scheduled and that amount will be reserved. Also, the task will be limited to max usage.

@akvadrako, I agree it's allot clearer like this.

@samuelkarp, please don't leave us - compose users - hanging with no support for this feature!

**Comment by PepijnK** [comment]
Hmmm, I'm doubting if this feature request is realistic. How would this soft limit work with regards to auto-scaling? When to decide to pop another instance? If the docker host decides to add another container to the instance, would it have to kill and restart the others in order to max-out memory consumption? 

I'm actually in favor of pre-determined bahavior, as all proposals here would imply a dynamic behaviour that you don't want -- especially not in production environments, so I doubt the usefulnes of it since you want to keep dev/test/prod as equal as possible (that's why you chose Docker in the first place).

**Comment by mpestritto** [comment]
Hi @samuelkarp

Was this just rolled out to the web console?  If so, I'm not sure what isn't supporting the change - the ecs-agent or the aws-cli?  Do you know which this could be related to?

Thanks.

`Parameter validation failed: Unknown parameter in containerDefinitions[0]: "memoryReservation", must be one of: name, image, cpu, memory, links...`

<img width="407" alt="screen shot 2016-08-15 at 3 53 37 pm" src="https://cloud.githubusercontent.com/assets/844201/17677369/7caeae1c-6300-11e6-9d96-ac682470bdc6.png">

**Comment by tedder** [comment]
Sir Jeff put up a post: https://aws.amazon.com/about-aws/whats-new/2016/08/amazon-ec2-container-service-now-supports-networking-modes-and-memory-reservation/

It's explained in the docs: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definitions

Now waiting for it to trickle down to CloudFormation so I can use it.

**Comment by CameronGo** [comment]
The hard limit memory is still a required field.  Need to do some experimentation to try and figure out how these two work together and impact the placement/availability of placement for tasks on a host.

**Comment by tedder** [comment]
Based on the docs, I don't think setting a memory field will affect placement if the memoryReservation is set.

**Comment by CameronGo** [comment]
Ahh - I didn't read closely enough.  I think you are right.  Also, the phrasing of this seems to address my comment, "You must specify a non-zero integer for one or both of memory or memoryReservation in container definitions. "

**Comment by tedder** [comment]
Ha, and I missed the 'one or both' clause.

**Comment by mpestritto** [comment]
Yes - I am setting both.  The only thing I changed was adding the memoryReservation to my config file.  Unfortunately, the `aws ecs register-task-definition` call from command line fails with what is below.  Any ideas if this is an aws api issue?  aws-cli issue?

Curious to see if anyone was able to get it working from command line.  As a side note -- works fine from aws web console.

Will gladly transfer this discussion to another thread.

`
"memory": 384,
"memoryReservation": 128,
`

`
jenkins@:~/workspace/project-name$ aws ecs register-task-definition --family api-workflow-www-staging --cli-input-json file://project-name-v_189.json

Parameter validation failed:
Unknown parameter in containerDefinitions[0]: "memoryReservation", must be one of: name, image, cpu, memory, links, portMappings, essential, entryPoint, command, environment, mountPoints, volumesFrom, hostname, user, workingDirectory, disableNetworking, privileged, readonlyRootFilesystem, dnsServers, dnsSearchDomains, extraHosts, dockerSecurityOptions, dockerLabels, ulimits, logConfiguration
`

**Comment by tedder** [comment]
I bet you'll need to wait for the awscli to be updated. Typically the reference implementations (java, ruby, botocore/awscli/boto3) get updated within the same day of new features, others can take longer. Here's where to watch for a new version of awscli: https://aws.amazon.com/releasenotes/CLI

You can watch all of them here: https://aws.amazon.com/releasenotes

And I publish an RSS feed of it here: http://tedder.me/rss/aws-release-notes.xml

**Comment by mpestritto** [comment]
Great -- Thanks @tedder I'll look around.  Appreciate it.

**Comment by CameronGo** [comment]
Wonder what version of the ECS agent has to be running.

**Comment by samuelkarp** [comment]
Hey all,

As you might have noticed, we've now launched the ability to set a soft memory limit as per [my proposal](https://github.com/aws/amazon-ecs-agent/issues/155#issuecomment-232227172).  You can see the launch announcement here: https://aws.amazon.com/about-aws/whats-new/2016/08/amazon-ec2-container-service-now-supports-networking-modes-and-memory-reservation/.

To use the new `memoryReservation` field in your task definition, you must be running ECS agent version 1.5.0 or greater and Docker version 1.9.0 or greater.

You can set `memoryReservation` in the ECS console today.  The AWS CLI and SDKs will be updated with the new field soon.

Please let us know if you have any further questions.

Thanks,
Sam

**Comment by tallavi** [comment]
Still wondering if there's a way to use the new feature in a **ecs-cli compose** command. Anyone knows?

**Comment by samuelkarp** [comment]
@tallavi Can you open a separate issue for tracking this on the [Amazon ECS CLI project](https://github.com/aws/amazon-ecs-cli)?

**Comment by tallavi** [comment]
Done.

**Comment by mpestritto** [comment]
Following-up .  It was a boto issue.  PR is up.
https://github.com/boto/botocore/pull/1006

**Comment by benjaminwai** [comment]
Taking a stab on Elastic Beanstalk I tried the "memoryReservation" param in multi-containers' Dockerrun.aws.json and it is returning "Service:AmazonECS...: Invalid setting for container... At least one of 'memory' or 'memoryReservation' must be specified'. I guess eb is not yet passing "memoryReservation"? Looking forward to be able to use it in eb.

**Comment by ssorathia** [comment]
Any update on when this would be available for EB?  I'm still seeing the following: `Service:AmazonECS, Code:ClientException, Message:Invalid setting for container 'app1'. At least one of 'memory' or 'memoryReservation' must be specified., Class:com.amazonaws.services.ecs.model.ClientException`

And here is my Dockerrun.aws.json file showing that it's configured:
`"essential": true,

      "memoryReservation": 64,
      "logConfiguration": {
`

But still no luck.  Considering this was in ECS quite some time ago, I'm wondering if something is broken with EB.

**Comment by vinayan3** [comment]
@ssorathia Please see this forum post https://forums.aws.amazon.com/message.jspa?messageID=747465#747465 

ElasticBeanStalk is not broken but does not support the new parameter yet. As the AWS developer says they do not have a timeline to it being fixed.

I was really hoping for this feature to be accessible through ElasticBeanStalk because that's how I deploy things onto ECS these days.

**Comment by ssorathia** [comment]
@vinayan3 Thanks so much for that link!  For some reason my search didn't yield that post!  Thanks for helping me out, at least now I know I'm not crazy.  I must have checked my spelling a dozen times!  :)

**Comment by danilobuerger** [comment]
Sadly this is still missing from Cloudformation :-(

**Comment by brewboy** [comment]
+1

**Comment by samuelkarp** [comment]
@danilobuerger @brewboy The `MemoryReservation` field is available in the [AWS::ECS::TaskDefinition](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html) type in CloudFormation.

**Comment by yololftw** [comment]
@samuelkarp Is this option exposed in aws batch?
