### ISSUE TITLE
Metrics collection triggers Docker memory leak

### ISSUE THREAD

**Issue by joshgarnett** [aws/amazon-ecs-agent#505]
Metrics collection is currently triggering a memory leak in Docker.  See https://github.com/docker/docker/issues/21837 and https://github.com/docker/docker/issues/25924 

1.10 added support for using docker stats for metrics collection.  After running the latest version of the agent for a little over a week, we've observed high memory and cpu usage in dockerd.  Stopping the ECS agent immediately reduced the CPU usage of dockerd.

**Comment by samuelkarp** [comment]
@joshgarnett Thanks for bringing this to our attention.  Are you seeing this on all versions since 1.10 or only a specific version?  We have a [known issue](https://github.com/aws/amazon-ecs-agent/issues/488) with versions 1.11.1 and 1.12.0 that we're fixing that might be exacerbating this problem.

**Comment by joshgarnett** [comment]
The only version >= 1.10 I've used so is 1.11.1.

**Comment by samuelkarp** [comment]
@joshgarnett We've released [1.12.1](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.12.1).  Can you try the new version and let us know if the problem recurs?

**Comment by rbravo-avantrip** [comment]
We have the ecs-agent (1.12.1) running on Ubuntu 14.04.5 (docker 1.11.2).
We see that docker daemon leaks memory when ecs-agent container is running. When we stop ecs-agent, docker daemon stops leaking memory. Not sure whether or not this is the same issue.
We have only application container that is iddle.

The same conditions but running on ECS Optimized AMI do not produce leaking (same versions).
What could happen?

**Comment by rbravo-avantrip** [comment]
It is related to the "Storage Driver: aufs", instead the driver 'devicemapper' that is used on ECS Optimized AMI.
See this:
# lsof -n 2>/dev/null|grep docker|grep deleted|wc -l
33640
Example line:
docker    31746             root   38r     FIFO               0,16      0t0    3882392 /run/docker/libcontainerd/11084e649e64af4a619e9e8edc2dfe2c93e009c35d8de538bb016d05721eeb2a/3b6b4ef9ee22f144c1384a9839758406b2df8266449be6668a4c190b40016843-stderr (deleted)


That number grows and grows only when ecs-agent is running. The total available memory (4GB in our case) is exhausted in a day, and the VM crashes.

**Comment by Tomdarkness** [comment]
@samuelkarp This still occurs in v1.13.1. On our staging environment this causes each ec2 instance to have a baseline 20% CPU usage, from the docker daemon, despite the containers running on the ec2 instance doing absolutely nothing. Same on production with the 20% CPU usage, except the containers are doing things - essentially we have to scale up 20% to deal with increased CPU usage from docker.

**Comment by Tomdarkness** [comment]
Here's a graph from cloudwatch that illustrates the problem. It's a graph of CPU usage reported by ECS vs CPU usage as reported by the EC2 autoscaling group:

![ecs-vs-ec2-prod](https://cloud.githubusercontent.com/assets/1273529/20686544/15bac106-b5b1-11e6-998d-69ed9dd8a865.PNG)

**Comment by samuelkarp** [comment]
@Tomdarkness Thanks for reporting.  Can you describe your staging environment a bit?  What Docker version and Linux distribution are you running?

As far as I can tell, this is the same issue reported at https://github.com/docker/docker/issues/21837 which looks like it's still not yet fixed in Docker.

**Comment by jc21** [comment]
An issue with `docker stats` would make sense for my particular issue relating to this.

I encounter a CPU usage creep when I deploy a Beanstalk Multi-container Docker. In this container, I am running 2 docker containers, one is a nodejs express server and the other is a apache/php web server. Over time the cpu will gradually increase even with no activity in the docker server containers. Restarting the docker process on the EC2 server reduces the CPU load, but then it creeps up again.

`64bit Amazon Linux 2016.09 v2.2.0 running Multi-container Docker 1.11.2 (Generic)`

When I run these docker apps separately on their own Beanstalk single Docker containers (thus, without ECS), there is no CPU creep.

**Comment by Tomdarkness** [comment]
@samuelkarp We're running CoreOS 1122.3.0 and Docker 1.10.3. Been stuck on this version of Docker for a while due to a deadlock issue in later versions which has only just recently been fixed.

Is it possible to add a configurable option for the frequency the ECS agent queries the container stats? We'd happily trade some stats granularity for reduced CPU impact.

**Comment by Tomdarkness** [comment]
Oh, forgot to mention. We also introduced a couple of ec2 instances into the ECS cluster with the ECS agents stat collection disabled. Those ec2 instances on average over a couple of weeks has a fairly significant reduction in CPU usage compared to the other ec2 instances despite being scheduled with fairly similar workloads.

**Comment by joshgarnett** [comment]
I'm not sure what DataDog is doing differently, but I've had no issues with their docker stats collection.

**Comment by samuelkarp** [comment]
@Tomdarkness The ECS agent [streams the stats from Docker](https://github.com/aws/amazon-ecs-agent/blob/v1.13.1/agent/stats/container.go#L98-L109) rather than querying at a given frequency, so they're just collected as fast as Docker produces them (~ 1/s).

@joshgarnett I haven't looked at DataDog, but the other way to collect stats is examining the cgroup stat information directly.  We used to do that before `docker stats` was available, but correlating the cgroups back to containers ties you very tightly to Docker's implementation.  In Docker 1.11, some of the implementation details changed (see https://github.com/aws/amazon-ecs-agent/issues/387#issuecomment-215506004 for details) and broke stats collection for the ECS agent; we migrated to consuming `docker stats` as that's an interface instead of an implementation detail and should (at least in theory) protect the ECS agent from breaking like this again.

**Comment by piontec** [comment]
Probably I also experienced this problem. We got docker running on AWS on x1.32xlarge instance. The instance has plenty of free resources, yet docker performance is really bad. We use constant container monitoring with telegraf + prometheus stack. Reporting performance stats of a single container takes about 2s:
```
# time curl --unix-socket /var/run/docker.sock 'http:/containers/7c4b44ebf578/stats?stream=false' > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5412    0  5412    0     0   2975      0 --:--:--  0:00:01 --:--:--  2975

real	0m1.831s
user	0m0.004s
sys	0m0.008s
```
while listing all containers takes 160ms:
```
# time docker ps > /dev/null

real	0m0.163s
user	0m0.092s
sys	0m0.060s
```

Info about our host:
```
# docker info
Containers: 421
 Running: 407
 Paused: 0
 Stopped: 14
Images: 703
Server Version: 1.12.4
Storage Driver: aufs
 Root Dir: /opt/io1/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3426
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 128
Total Memory: 1.876 TiB
Name: ip-10-69-11-89
ID: UGZS:UFD3:GB4C:W5MX:JU2L:K7PH:6ZWS:4GPM:27Q5:UNNN:X3DC:YDT7
Docker Root Dir: /opt/io1/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```
```
# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 7869914
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 7869914
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
Let me know if I can provide any additional data to help investigate this.

**Comment by MrSaints** [comment]
We've recently upgraded to the latest recommended ECS AMI, and we noticed that `dockerd` appears to be using a lot of memory.

The actual processes in the container do not appear to be using much memory at all (they aren't growing), but for some reason, the total memory usage in the instance is growing.

I'm unsure if it's related to `docker stats` as I disabled stats collection, and it does not seem to have eradicated the problem. Are there any AMIs with an older version of Docker Engine? I tried using the older AMIs, but for some reason they appear to all be using the latest Docker Engine.

**Comment by samuelkarp** [comment]
> I tried using the older AMIs, but for some reason they appear to all be using the latest Docker Engine (as if it's being updated on-the-fly).

Docker 1.12.6 is a [security update](https://alas.aws.amazon.com/ALAS-2017-783.html) which gets [updated on first boot](https://aws.amazon.com/amazon-linux-ami/faqs/#auto_update).

We do not recommend disabling security updates, but if you need instructions for doing so see https://github.com/aws/amazon-ecs-agent/issues/664#issuecomment-272305195.

> I'm unsure if it's related to `docker stats` as I disabled stats collection, and it does not seem to have eradicated the problem.

We're at present unaware of other issues that would cause `dockerd` to consume larger amounts of memory.  If you have reproduction steps for this, can you share them so we can investigate?

**Comment by freedomofkeima** [comment]
Hi,

After updating to ECS Agent 1.13.1 and Docker 1.12.6 (previously 1.11.2) w/ ECS-optimized AMI for several days, we are also experiencing performance degradation here. The CPU consumption is ~20% higher than the previous version. The memory leak problem appears to be there from 1.11.2, but it seems getting worse with the latest update.

I'll let you know if I find any newest information after some experiments.

**Comment by aaithal** [comment]
Hi @freedomofkeima, thank you reporting this. Can you please let us know what value the y-axis is representing here? Also, was the same kind of workload being executed on the instance between the before and after scenarios? We'll work on validating this spike from our end as well. Thanks!

**Comment by aaithal** [comment]
Hello everyone,  i'm closing this issue since there's been no activity on this for a while. Please get back to us if this re-occurs. 

Thanks,
Anirudh

cc @freedomofkeima
